# Generated by Django 5.1.5 on 2025-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BunkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDays', models.IntegerField()),
                ('totalAttendanceNeeded', models.IntegerField()),
                ('presentAttendance', models.IntegerField()),
                ('daysGone', models.IntegerField()),
                ('resultMessage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
